#! /usr/bin/perl -w

$usr=`whoami`;
chomp($usr);

	#=================
	# REMOVE ZOMBIES
	#=================
@removelist=("avgrosr","avggps","kermit","expect","perl");
foreach $xx (@removelist){
	$cmd="ps -u $usr -o pid,command | grep \"$xx\"";
	#print"test 1 cmd = $cmd\n";
	@pslist = `$cmd`;
	#$ii=0; foreach(@pslist){chomp($_); print"test 0 $ii, $pslist[$ii]\n"; $ii++}
	foreach $pscmd (@pslist){
		chomp($pscmd);
		#print"test 2 $pscmd\n";
		if( $pscmd =~ /grep/){
			#print"test 3 $pscmd\n";
		} else {
				# remove leading spaces
			$pscmd =~ s/^\s+//;
			@d=split/[ ]+/,$pscmd;
			#$ii=0; foreach(@d){chomp($_); print"$ii, $d[$ii]\n"; $ii++} die;
			$cmd="kill $d[0]";
			print"$pscmd -- $cmd\n";
			`$cmd`;
		}
	}
}
exit;

