#!/usr/bin/perl -w

#  1. Call after 'Stoprosr'
#  2. ArchiveRosr
#
#  Wipes clean the ROSR/data folder
#    Asks permission before
#  
#  Call:  perl ClearRosrData
#  
#  Output: none
# 

use lib $ENV{MYLIB};
use perltools::MRutilities;
use perltools::MRtime;

	## DATA PATH
my $datapath="$ENV{HomePath}/swmain/apps/ROSR/data";
my $ans='n';
if($#ARGV >= 0){
    $ans=shift();
    #print"$ans was in the commannd line.\n";
} 
else {
    print"ClearRosrData: WARNING  This process will delete 
everything from the ROSR/data folder. 
Call \"Archive\" to backup all collected data.
";    
    print"Proceed to delete?  (y or n): ";
    $ans=<>;
    chomp($ans);
    print"You entered $ans\n";
}
if($ans =~ /y/i){
	print"ClearRosrData\n";
	my $cmd="rm -r $datapath/*";
	#print"cmd=$cmd\n";
	system $cmd;
} else {
	print"No delete.\n";
}

exit 0;
