#!/usr/bin/perl -w

use lib $ENV{MYLIB};
use perltools::MRtime;
use perltools::MRutilities;
use Time::Zone;

my @f = ('rosr_raw','rosr_avg','gps_raw','gps_avg');
my @d = (600, 1800, 600, 600);
my @v = ();

#       rosr_raw   1521529544      3    600   OK
print"  file       last sec        dif  lim   status\n";
printf"  NOW =      %10d\n",now();
my $os=tz_local_offset();

	# SELECT STREAM
my $is;
for($is=0; $is<=$#f; $is++){
	my $f=$f[$is];
		# FILE MOD TIME
	my $mtime = (stat `LastDataFolder $f`)[9]-$os;
	my $age = now() - $mtime;
	printf"%10s   %10d   %4d   %4d   ",$f,$mtime,$age,$d[$is];
	if ($age > $d[$is]){print"FAIL\n"; push @v,0}
	else{ print"OK\n"; push @v, 1;  }
}
my $good=1;
print"@v\n";
foreach(@v){if($_ == 0){$good=0}}
#print"good = $good\n";
`echo $good > /tmp/tmpdaq`;

exit 0
