#!/usr/bin/perl -X

use lib $ENV{MYLIB};
use perltools::MRutilities;

my $fname = shift();
my $str = shift();
my $strout;

if ( ! -f $fname ) {
	print "file $fname does NOT exist\n";
	exit 1;
}

#print "Search file $fname for string $str:\n";
$strout = FindInfo($fname, $str,':');

print "$strout\n";# This is necessary for the expect program
exit 0;

