#!/usr/bin/perl -X
#   ./LastAvg rad_avg (or 'gps_avg', 'wxt_raw', etc)

if($#ARGV<0){print"
  LastDataRecord error.  Include data file tag,
  e.g. \"LastDataRecord rosr_av\".
"}
my $a = shift();
my $s = `LastDataFolder $a`;
chomp $s;
# print"datafolder = $s\n"; die;

if ($s eq 0 ){print"0"; exit 1}
else {
	$s =~ s/^\s+//;
	system "tail -1 $s";
	exit 0;
}
