#! /usr/bin/perl

use lib $ENV{DAQLIB};
use perltools::MRtime;

$finx="$ENV{HomePath}/rosrsim.txt";
$fin="simulate/rosr.txt";
if(-f $finx){
	$fin=$finx;
}
while (1) {
	open(F,"<$fin") or die("fin error\n");

	# Loop through all the data records.
	while (<F>) {
		chomp( $str = $_);

		# STRIP OFF THE BEGINNING TIME USING SED
		print"$str\r\n";
		sleep(2);
	}
	print"Starting over\n";
	close F;
}
