#! /usr/bin/perl

use lib $ENV{DAQLIB};
use perltools::MRtime;

$fin="simulate/rosr.txt";

my $irec = 0;
my $i1;

while (1) {
	$irec = 0;
	open(F,"<$fin") or die("fin error\n");

	# Loop through all the data records.
	while (<F>) {
		chomp( $str = $_);

		# STRIP OFF THE BEGINNING TIME USING SED
		print"$str\r\n";
		sleep(2);
		$irec++;
	}
	print"Starting over\n";
	close F;
}
