#!/usr/bin/perl -w

# SERVER MODULE WAITS FOR A REQUEST

# use lib $ENV{DAQLIB};
# use perltools::MRtime;
# use perltools::MRutilities;
use IO::Socket;

$serverip=shift();
$serverport=shift();
print"socket = $serverip $serverport\n";

my $sock = new IO::Socket::INET (
	LocalHost => $serverip,
	LocalPort => $serverport,
	Proto => 'tcp',
	Listen => 1,
	Reuse => 1,
);
die "Could not create socket: $!\n" unless $sock;

my ($size,$new_sock,$str);
$str="ok\n";
while(1){
	$new_sock = $sock->accept();
	while(<$new_sock>) {
	    print $_;
	}
}
close($sock);
