#!/usr/bin/expect --
#Note: the file .kermrc has the command "prompt k>>"

# v3 141016 
# v4 180523 -- include COM2 to mini PC
# 20180524T030502Z
log_user 0;

set setupfile "$env(DAQSWFOLDER)/setup/su.txt"

#==============
## PASSWORD
#==============
spawn -noecho getsetupinfo $setupfile "DAQ PASSWORD"
expect -re "(\.*)(\r)";
set password $expect_out(1,string)
#send_user "DAQ PASSWORD: $password\n";

#==============
## READ SETUP FILE FOR IP ADDRESS
#==============
spawn -noecho getsetupinfo $setupfile "GPS PORT"
expect -re "(\.*)(\r)";
set gpsport $expect_out(1,string)
send_user "GPS PORT: $gpsport\n";

#====================
# GPS INPUT OPTION
#====================
if { $gpsport == 0 } { 
	# SIMULATE
	send_user "SIMULATE GPS--end\n";
	exit 0;
} elseif {$gpsport == 1} {
	# GPS CONNECTION
	spawn -noecho getsetupinfo $setupfile "SERIAL GPS"
	expect -re "(\.*)(\r)";
	set gpscom $expect_out(1,string)
	send_user  "GPS 232COM: $gpscom\n"
	exit 0;
} elseif {$gpsport == -1} {
	# FIXED
	spawn -noecho getsetupinfo $setupfile "GPS FIXED LATITUDE"
	expect -re "(\.*)(\r)";
	set fixedlat $expect_out(1,string)
	spawn -noecho getsetupinfo $setupfile "GPS FIXED LONGITUDE"
	expect -re "(\.*)(\r)";
	set fixedlon $expect_out(1,string)
	send_user "GPS FIXED LAT $fixedlat, LON $fixedlon\n";
	exit 0;
} else {
	# HUB SERIAL SERVER
	spawn -noecho getsetupinfo $setupfile "SERIAL HUB IP"
	expect -re "(\.*)(\r)";
	set hubip $expect_out(1,string)
	send_user "SERIAL HUB IP: $hubip, GPS PORT: $gpsport"
}

	
	# START PROCESS -- KERMIT FOR MODEM
	spawn sudo kermit
	expect {
		"assword" {
			send "r0srr0sr\n"
		}
		">>" { send "\n" }
	}
	set PDS $spawn_id
	set timeout 4

	expect {
		timeout {"KERMIT FAILS TO OPEN\n"; exit 1}
		">>"
	}

	## OPEN THE PORT
	send "set host $hubip $portnumber\r"
	expect ">>"
	#send_user "set host $hubip $portnumber\n";
	
	## FINE TUNING TCP/IP
	send "set tcp keepalive on\r\n"
	expect ">>"
	send "set tcp linger\r\n"
	expect ">>"
	send "set tcp nodelay on\r\n"
	expect ">>"
			# v2 
	send "set telnet echo local\r\n"
	expect ">>"

	## this is important for using the rsr menu
	## raw means send CR by itself, not CRLF and NOT CRNul
	send "set telnet newline-mode nvt raw\r\n"
	expect ">>"

	## CONNECT 
	send "connect\r"
	expect {
		"Conn*---"  {send_user "CONNECTED\r\n"}
		timeout {send_user "TIMEOUT, NO CONNECT"; exit 1}
	}
	set spawn_id $PDS
	interact

## RS232 SERIAL DIRECT TO COM	
} else {
	spawn sudo kermit
	expect {
		"assword" {
			send "r0srr0sr\n"
		}
		">>" { send "\n" }
	}
	set GPS $spawn_id
	set timeout 4
	expect {
		-i GPS
		timeout {"KERMIT FAILS TO OPEN\n"; exit 1}
		">>"
	}
	
	spawn -noecho getsetupinfo $setupfile "SERIAL GPS"
	expect -re "(\.*)(\r)";
	set gpscom $expect_out(1,string)
	send_user "SERIAL GPS: $gpscom\n"

	## OPEN THE PORT
	set spawn_id $GPS
	#send_user "set line $gpscom\n";
	send "set line $gpscom\r"
	expect ">>"
	## SPEED
	#send_user "set speed 9600\n"
	send "set speed 9600\r\n"
	## DUPLEX
	send "set duplex full\r"
	expect ">>"
	## LOCAL ECHO
	send "set local-echo on\r"
	expect ">>"
	## FLOW CONTROL
	send "set flow none\r"
	expect ">>"
	## CARRIER WATCH
	send "set carrier-watch off\r"
	expect ">>"
	## LOG
	send "log session ../data/capture.txt append\r"
	expect ">>"
	## CONNECT 
	send "connect\r"
	expect {
		"Conn*---"  {send_user "TTY CONNECTED\n"}
		timeout {send_user "TIMEOUT, NO CONNECT"; exit 1}
	}
	set spawn_id $GPS
	interact
}
exit; 

exit 0
