#!/usr/bin/expect --
#Note: the file .kermrc has the command "prompt k>>"

# v3 141016 
# v4 180523 -- include COM1 to mini PC
# v5 200826 -- apt install kermit fail because of an upgrade in apt. I
#              got a new version from Cruz but it is buggy. 

log_user 0
set setupfile "$env(DAQSWFOLDER)/setup/su.txt"

#==============
## READ SETUP FILE FOR IP ADDRESS
#==============
spawn -noecho getsetupinfo $setupfile "SERIAL HUB IP";
expect -re "(\.*)(\r)";
set hubip $expect_out(1,string) ;
#send_user "SERIAL HUB IP: $hubip\n";

## SERIAL SERVER VIA ETHERNET
#send_user "serial server hub\n"
#==============
## READ SETUP FILE FOR PORT NUMBER
#==============
spawn -noecho getsetupinfo $setupfile "GPS PORT"
expect -re "(\.*)(\r)";
set portnumber $expect_out(1,string)

# START PROCESS -- KERMIT FOR MODEM
spawn sudo kermit
expect {
	"assword" {
		send "r0srr0sr\n"
	}
	">>" { }
	"C-Kermit>" { 
		send "prompt k>>\n" ;
		#send_user "39 snd prompt\n" ; 
	}
}
set PDS $spawn_id
set timeout 3

send "prompt k>>\n" ;
expect {
	-i PDS
	timeout {send_user "47 KERMIT FAILS TO OPEN\n"; exit 1}
	"C-Kermit>" { 
		send "prompt k>>\n" ;
		#send_user "50 snd prompt again\n" ;
	}
	">>" { }
}

## OPEN THE PORT
send "set host $hubip $portnumber\r"
expect ">>"
send_user "set host $hubip $portnumber\n";

## FINE TUNING TCP/IP
send "set tcp keepalive on\r\n"
expect ">>"
send "set tcp linger\r\n"
expect ">>"
send "set tcp nodelay on\r\n"
expect ">>"
		# v2 
send "set telnet echo local\r\n"
expect ">>"

## this is important for using the rsr menu
## raw means send CR by itself, not CRLF and NOT CRNul
send "set telnet newline-mode nvt raw\r\n"
expect ">>"

# LOG THE SESSION
set logpath "$env(DAQDATAFOLDER)/capture_gps.txt"
#send_user "log to $logpath\n";
send "log session $logpath append\r\n"
expect ">>"

## CONNECT 
send "connect\r"
expect {
	"Conn*---"  {send_user "GPS CONNECTED\r\n"}
	timeout {send_user "86 GPS TIMEOUT, NO CONNECT"; exit 1}
}

set spawn_id $PDS
interact

exit; 

exit 0
