#!/usr/bin/expect --

set PROGRAMNAME Z_gps
set VERSION 09
set EDITDATE 180202; #150414;	#150410;	#150214		;#141024  ;#130706

set loguser 0;#   test 0-quiet, 1=verbose
log_user $loguser;

global GPS GPSPID GPSAV GPSAVPID
global infoname

#========================================================
#		PROCEDURE TO SIMULATE GPS #v9
#========================================================
proc SpawnGpsSimulate { } {
	global GPS GPSPID infoname
		# Spawn simulate_gps
	set GPSPID [spawn perl simulate_gps]
	set GPS $spawn_id
	write_info $infoname "SPAWN GPS SIMULATE, spawn_id = $GPS, pid = $GPSPID"
}
#========================================================
		# PROCEDURE TO CONNECT TO GPS  v3
#============================================================
proc SpawnGps { hubip gpsport gpscomport} {
	global GPS GPSPID infoname
	if { [string first "dev" $hubip] == -1 } {
		set str [spawn_kermit $hubip $gpsport]
		set GPS [lindex $str 0];    
		set GPSPID [lindex $str 1];
		send_user "SPAWN GPS KERMIT, IP=$hubip, port=$gpsport, spawn_id=$GPS, pid=$GPSPID\n"
		write_info $infoname "SPAWN GPS KERMIT, IP=$hubip, port=$gpsport, spawn_id=$GPS, pid=$GPSPID"
	} else {
		set str [spawn_kermit232 $gpscomport]
		set GPS [lindex $str 0];
		set GPSPID [lindex $str 1];
		write_info $infoname "SPAWN KERMIT232, IP=$hubip, spawn_id=$GPS, pid=$GPSPID"
		send_user "SPAWN KERMIT232, IP=$hubip, spawn_id=$GPS, pid=$GPSPID\n"
	}
}
#=====================================
#   PROCEDURE TO START AVGGPS PROGRAM
#==================================
proc SpawnAvgGps { setupfile } {
	global GPSAV GPSAVPID infoname
	set GPSAVPID [spawn perl avggps $setupfile]
	set GPSAV $spawn_id
	write_info $infoname "SPAWN GPSAV spawn_id = $GPSAV, pid = $GPSAVPID"
			# PROGRAM REPLY
	expect {
		eof {
			send_user "AVGGPS STARTUP, eof\n"
			exit 1
		}
		"GPS--" {
			send_user "AVGGPS is ready, spawn_id=$GPSAV,  pid = $GPSAVPID\n"
		}
	}
}

#====================================================================
# PROCEDURE WRITE_INFO
# input
#  fname = fullfile name towrite the info string
#  str=the string to write
#=============
proc write_info {fname str} {
	set str [timestamp -gmt -format "%y%m%d,%H%M%S,"]$str
	exec echo $str >> $fname
	return $str
}

#===========================================================================
# PROCEDURE TO CONNECT TO A PORT USING KERMIT
# input
#	hubip = ip#
#   portnumber
#Note: .kermrc file line = prompt k>>
#============================================
proc spawn_kermit {hubip portnumber} {
	global GPS GPSPID infoname
			# START PROCESS -- KERMIT
	set GPSPID [spawn kermit]
	set GPS $spawn_id;
	set timeout 4	
	expect {
		timeout {send_user "KERMIT FAILS TO OPEN\n"; exit 1}
		">>"
	}
	
	write_info $infoname "KERMIT PORT $hubip  $portnumber";
			# OPEN THE PORT
	send "set host $hubip $portnumber\r"
	expect ">>"
	send "set tcp keepalive on 0\r\n"
	expect ">>"
	send "set tcp linger OFF\r\n"
	expect ">>"
	send "set tcp nodelay on\r\n"
	expect ">>"
	send "set telnet echo local\r\n"
	expect ">>"
			# this is important for using the rsr menu
			# raw means send CR by itself, not CRLF and NOT CRNul
	send "set telnet newline-mode nvt raw\r\n"
	expect ">>"
			# CONNECT 
	send "connect\r"
	expect {
		"Conn*---"  {send_user "PORT $portnumber CONNECTED\n"; return $spawn_id;}
		timeout {send_user "TIMEOUT, NO CONNECT"; exit 1}
	}
}
#===========================================================================
# PROCEDURE TO CONNECT RS232 TO A PORT USING KERMIT
# input
#	serialport = full path name for the serial port, e.g. /dev/tty.usbserial0
#   baud = desired baud rate, e.g. 9600
#============================================
proc spawn_kermit232 {hubip} {
	global infoname
			# START PROCESS -- KERMIT
	set pid [spawn sudo kermit]
	expect {
		"assword" {
			send "r0srr0sr\n"
		}
		">>" { send "\n" }
	}
	send_user "!> pid = $pid\n";
	set timeout 4
	expect {
		timeout {"KERMIT FAILS TO OPEN\n"; exit 1}
		">>"
	}
			# OPEN THE PORT
	## OPEN THE PORT
	send "set line $hubip\r"
	expect ">>"
	#send_user "set line $hubip\n";
	## SPEED
	send "set speed 9600\r"
	## DUPLEX
	send "set duplex full\r"
	expect ">>"
	## LOCAL ECHO
	send "set local-echo on\r"
	expect ">>"
	## FLOW CONTROL
	send "set flow none\r"
	expect ">>"
	## CARRIER WATCH
	send "set carrier-watch off\r"
	expect ">>"
	## LOG
	send "log session ../data/capture.txt append\r"
	expect ">>"
	## CONNECT 
	send "connect\r"
	expect {
		"Conn*---"  {send_user "232 CONNECTED\n"}
		timeout {send_user "TIMEOUT, NO CONNECT"; exit 1}
	}
	set out $spawn_id;
	lappend out $pid
	return $out
}
#==================== END PROCEDURES =============================================


set infoname "$env(DAQDATAFOLDER)/info_gps.txt"
send_user "infoname = $infoname\n";

write_info $infoname "===== $PROGRAMNAME, V $VERSION, $EDITDATE =============="


		# SETUP FILE DEFINED
set setupfile  [lindex $argv 0]
write_info $infoname "SETUPFILE: $setupfile   "
## SEE IF THE SETUP FILE EXISTS
if [catch {open $setupfile} sufile] {
	send_user "Bad setup file: stop."
	exit 1
}

		# DATAPATH
spawn -noecho getsetupinfo $setupfile "RT OUT PATH"
expect -re "(\.*)(\r)";
set datapath $expect_out(1,string)
write_info $infoname "DATAPATH = $datapath\n";

		## TIME WITH NO GPS
spawn -noecho getsetupinfo $setupfile "GPS DEAD TIME ALARM SECS"
expect -re "(\.*)(\r)";
set zdeadtime $expect_out(1,string);
write_info $infoname  "GPS DEAD TIME ALARM SECS: $expect_out(1,string)"

		# DEFINE THE PORTS 
spawn -noecho getsetupinfo $setupfile "GPS PORT"
expect -re "(\.*)(\r)";
set gpsport $expect_out(1,string)
write_info $infoname  "GPS PORT: $gpsport"
send_user "GPS PORT: $gpsport\n";
	#====================
	# GPS INPUT OPTION
	#====================
if { $gpsport == 0 } { 
	# SIMULATE
	send_user "SIMULATE GPS.\n";
	write_info $infoname  "SIMULATE GPS.";
	SpawnGpsSimulate;
} elseif {$gpsport == 1} {
	# GPS CONNECTION
	write_info $infoname  "GPS RS232";
	spawn -noecho getsetupinfo $setupfile "SERIAL GPS"
	expect -re "(\.*)(\r)";
	set gpscom $expect_out(1,string)
	write_info $infoname  "GPS 232COM: $gpscom"
	send_user  "GPS 232COM: $gpscom\n"
	set hubip "rs232 device";
	SpawnGps $hubip $gpsport $gpscom
} elseif {$gpsport == -1} {
	# FIXED
	spawn -noecho getsetupinfo $setupfile "GPS FIXED LATITUDE"
	expect -re "(\.*)(\r)";
	set fixedlat $expect_out(1,string)
	spawn -noecho getsetupinfo $setupfile "GPS FIXED LONGITUDE"
	expect -re "(\.*)(\r)";
	set fixedlon $expect_out(1,string)
	write_info $infoname  "GPS FIXED LAT $fixedlat, LON $fixedlon";
	send_user "GPS FIXED LAT $fixedlat, LON $fixedlon\n";
	send_user "Exit Z_gps\n"; exit 0;
} else {
	# HUB SERIAL SERVER
	spawn -noecho getsetupinfo $setupfile "SERIAL HUB IP"
	expect -re "(\.*)(\r)";
	set hubip $expect_out(1,string)
	write_info $infoname  "SERIAL HUB IP: $hubip"
	send_user "SERIAL HUB IP: $hubip, GPS PORT: $gpsport"
	SpawnGps $hubip $gpsport $gpscom
}

		# GPSAV PROGRAM
SpawnAvgGps $setupfile


# =====================
# MAIN LOOP
#======================
		# COUNT GOOD RECORDS
set Nrecs 0
set day0 0 ;# to initiate the first raw file

set timemsg [timestamp]	;# --- MISSING INPUT TRANSMIT TIME
set timegps [timestamp]
set timegpslast 0	      		;# --- TIME OF THE LAST RECEIVED RAD

while 1 {
	set dt [timestamp]  ;# loop time
	
			# TIMEOUT
	if { [expr $dt - $timegps] > $zdeadtime } {
		send_user "NO RAW GPS IN $zdeadtime SECS.\n"
		set timegps $dt
		set dt0 $dt
	}
	
			# NEW DAY -- NEW FILES
	set day1 [timestamp -gmt -format "%j" -seconds $dt]
	if {$day1 != $day0} {
		set day0 $day1
		set fname [timestamp -gmt -format "%y%m%d" -seconds $dt]
		set rawname "$datapath/gps_raw_$fname.txt";
		puts "RAW FILE NAME = $rawname";
		if {[file exists $rawname]} {
		} else {
			set F [open $rawname w 0600]
			puts $F "nrec yyyy MM dd hh mm ss lat lon sog cog var"
			close $F
		}
		write_info $infoname "New day: rawname = $rawname"
	}
	#================
	# EXPECT FUNCTION -- WAITING FOR RESPONSE
	# ===============
	expect {
		-i $GPS
		"\\\$GPRMC*\\*??"  {
			set rawstr $expect_out(0,string);
			set rawstr [string trim $rawstr ]
			set timegps [timestamp] ;# record the time of the last gps
					# --- TRAP DUP TIMES ----
			while { $timegps <= $timegpslast } {
				set timegps [expr $timegps + 1 ]
			}
			set timegpslast $timegps;
			set spawn_id $GPSAV
			send "$rawstr\r\n"
			
			# SAVE TO RAW FILE
			set F [open $rawname a 0600]
			set rawstr [timestamp -gmt -format "$Nrecs %Y %m %d %H %M %S " -seconds $timegps]$rawstr
			puts $F $rawstr
            #send_user "$rawstr\n";
			close $F
					# SEND RAW TO AVG AND RCV RESPONSE
			set timeout 1
			set spawn_id $GPSAV
			expect {
				timeout { send_user "AVG timeout\n" }
				-re "<<(GPSRW.*)>>"	{send_user "$expect_out(1,string)\n"} 
			}
					# RECORD COUNT
			set Nrecs [expr $Nrecs + 1];
		}

		-i $GPSAV
		eof {
			SpawnAvgGps $setupfile $infoname
			write_info $infoname "AVGGPS fails.  RE-START AVGGPS, spawn_id = $GPSAV,   pid = $GPSAVPID\n";
		}
		-re "<<(GPSAV,.*?)>>\r\n" {send_user "$expect_out(1,string)\n";}
		
		#================== USER INPUT =========================================#
		-i $user_spawn_id  
		-re ".+" {
			set userstr $expect_out(0,string)
			send_user $userstr
			#=====================
			# QUIT & SEND SIGNOFF MESSAGE
			#====================
			if {[string match "*quit*" "<[string tolower $userstr]>"]} {
				write_info $infoname "USER QUIT\n";
				exit 0;
			}
			#=====================
			# WRITE A HEADER LINE
			#====================
			if {[string match "*h*" "<[string tolower $userstr]>"]} {
				send_user "PROGRAM $PROGRAMNAME, VERSION $VERSION, EDITDATE $EDITDATE\n";
						#  >20101226,195812,  41,0,1, -2.5,-1.5, 125,  514,3393,3394,3392,2340,2340,2355, 47.603,-122.288, 0.1,   0
				send_user " yyyyMMdd,hhmmss ormv sw0 sw1  ptch roll fgaz  kt b11mv b12  b13  b21  b22  b23   lat     lon     sog  cog \n";
			}
		}
	}
}

