#!/usr/bin/expect --
#Z_rosr_v6

set PROGRAMNAME Z_rosr
set VERSION 10
set EDITDATE 20200921,17;
# 
# V1 FROM Z_ROSR V20
#v4 use getgpsraw program 
#v5 tighten regex expression
#v6 rosr3 
#v7 rosr3 was hung up. I'll try to get it going.
#v8 simulate_rosr
#v9 include serial server or rs232
#v9.1 -- trying to get it to work
#v9.2 -- debug. Fix wirav and wirst files
#v9.4 -- debug mystery crash at new day -- see line 346
#v10 -- add sbdtx for iridium, see Z_rosr_bak

puts "
RUN PROGRAM $PROGRAMNAME, VERSION $VERSION, EDITDATE $EDITDATE"

set loguser 0;		#   v9.5 set to 0test 0-quiet, 1=verbose
log_user $loguser;

		# SETUP FILE DEFINED
set setupfile  [lindex $argv 0]
		## SEE IF THE SETUP FILE EXISTS
if [catch {open $setupfile} sufile] {
	puts "Setup file open fails, exit 1"
	exit 1
}
# else {
#	puts "SETUP FILE $setupfile --- EXISTS"
#}

global ROSR ROSRPID ROSRAV ROSRAVPID
global infoname
#========================================================
#		PROCEDURE TO SIMULATE ROSR #v8
#========================================================
proc SpawnRosrSimulate { } {
	global ROSR ROSRPID infoname
	set ROSRPID [spawn perl simulate_rosr]
	set ROSR $spawn_id
	write_info $infoname "SPAWN ROSR SIMULATE, spawn_id = $ROSR, pid = $ROSRPID"
	send_user "SPAWN ROSR SIMULATE, spawn_id = $ROSR, pid = $ROSRPID\n"
}
#========================================================
		# PROCEDURE TO CONNECT TO ROSR
#============================================================
proc SpawnRosr { hubip rosrport} {
	global ROSR ROSRPID infoname
	if { [string first "dev" $hubip] == -1 } {
		set str [spawn_kermit $hubip $rosrport]
		set ROSR [lindex $str 0];    
		set ROSRPID [lindex $str 1];
		send_user "SPAWN ROSR KERMIT, IP=$hubip, port=$rosrport, spawn_id=$ROSR, pid=$ROSRPID\n"
		write_info $infoname "SPAWN ROSR KERMIT, IP=$hubip, port=$rosrport, spawn_id=$ROSR, pid=$ROSRPID"
	} else {
		set str [spawn_kermit232 $hubip]
		set ROSR [lindex $str 0];    
		set ROSRPID [lindex $str 1];
		write_info $infoname "SPAWN KERMIT232, IP=$hubip, spawn_id=$ROSR, pid=$ROSRPID"
		send_user "SPAWN KERMIT232, IP=$hubip, spawn_id=$ROSR, pid=$ROSRPID\n"
	}
}
#==========================================
#   PROCEDURE TO START AVGROSR PROGRAM
#==========================================
proc SpawnAvgRosr { setupfile } {
	global ROSRAV  ROSRAVPID infoname
	set ROSRAVPID [spawn perl avgrosr $setupfile]
	set ROSRAV $spawn_id
	write_info $infoname "SPAWN ROSRAV spawn_id = $ROSRAV,  pid=$ROSRAVPID"
			# WAIT FOR THE STARTUP PROMPT
	set timeout 5
	expect {
				# REPLY FROM AVG PROGRAM
		"avgrosr--" {
			send_user "AVGROSR is ready\n"
		}
	}
}

#====================================================================
		# PROCEDURE WRITE_INFO
		# input
		#  fname = fullfile name towrite the info string
		#  str=the string to write
		# call:
		# write_info "/tmp/info" "This is a test."
#=====================================================================
proc write_info {fname str} {
	set str [timestamp -gmt -format "%Y%m%dT%H%M%SZ,"]$str
	exec echo $str >> $fname
	return $str
}

#===========================================================================
# PROCEDURE TO CONNECT TO A PORT USING KERMIT
# input
#	serialport = full path name for the serial port, e.g. /dev/tty.usbserial0
#   baud = desired baud rate, e.g. 9600
#============================================
proc spawn_kermit {hubip portnumber} {
	global infoname
			# START PROCESS -- KERMIT
	set pid [spawn kermit]
	expect {
		timeout {send_user "KERMIT FAILS TO OPEN\n"; exit 1}
		">>"
	}
	
			# OPEN THE PORT
	send "set host $hubip $portnumber\r"
	expect ">>"
	send "set tcp keepalive on 0\r\n"
	expect ">>"
	send "set tcp linger OFF\r\n"
	expect ">>"
	send "set tcp nodelay on\r\n"
	expect ">>"
	send "set telnet echo local\r\n"
	expect ">>"
			# this is important for using the rsr menu
			# raw means send CR by itself, not CRLF and NOT CRNul
	send "set telnet newline-mode nvt raw\r\n"
	expect ">>"
			# CONNECT 
	send "connect\r"
	expect {
		timeout {send_user "TIMEOUT, NO CONNECT"; exit 1}
		"Conn*---"  { }  #v15
	}
	set out $spawn_id;
	lappend out $pid
	return $out
}


#===========================================================================
# PROCEDURE TO CONNECT RS232 TO A PORT USING KERMIT
# input
#	serialport = full path name for the serial port, e.g. /dev/tty.usbserial0
#   baud = desired baud rate, e.g. 9600
#============================================
proc spawn_kermit232 {hubip} {
	global infoname
			# START PROCESS -- KERMIT
	set pid [spawn sudo kermit]
	expect {
		"assword" {
			send "r0srr0sr\n"
		}
		">>" { send "\n" }
	}
	send_user "!> pid = $pid\n";
	set timeout 4
	expect {
		timeout {"KERMIT FAILS TO OPEN\n"; exit 1}
		">>"
	}
			# OPEN THE PORT
	## OPEN THE PORT
	send "set line $hubip\r"
	expect ">>"
	#send_user "set line $hubip\n";
	## SPEED
	send "set speed 9600\r"
	## DUPLEX
	send "set duplex full\r"
	expect ">>"
	## LOCAL ECHO
	send "set local-echo on\r"
	expect ">>"
	## FLOW CONTROL
	send "set flow none\r"
	expect ">>"
	## CARRIER WATCH
	send "set carrier-watch off\r"
	expect ">>"
	## LOG
	send "log session ../data/capture.txt append\r"
	expect ">>"
	## CONNECT 
	send "connect\r"
	expect {
		"Conn*---"  {send_user "232 CONNECTED\n"}
		timeout {send_user "TIMEOUT, NO CONNECT"; exit 1}
	}
	set out $spawn_id;
	lappend out $pid
	return $out
}

#==================== SBD PROCEDURES v10 sbdtx =============================================
global SBD SBDPID
#===================================
# PROCEDURE TO CONNECT TO SBD  v13
# NOTE: Check for a valid sbdport before calling this.
#===================================
proc SpawnSBD { hubip sbdport }  {
	global SBD SBDPID
	set str [spawn_kermit $hubip $sbdport]
	set SBD [lindex $str 0];
	set SBDPID [lindex $str 1];
}
#v10 sbdi
#====================================================================
		# PROCEDURE TO SEND SBD MESSAGE  #v10 sbdtx
		# input
		#  str=the string to send
		#  sbdid = the spawn ID for the sbd modem
		#  ntries = no. of attempts for a "good" transmission
#====================================================================
proc sbdi {str sbdid ntries} {
	global infoname;
	set strlen [string length $str] ;
	## WAKE UP THE MODEM
	set timeout 1
	set i 0
# 	write_info $infoname "Begin sbdi"
	#===================
	# IS MODEM AWAKE?
	# ==================
	while {$i < 5} {
		incr i 1
		send -i $sbdid "at\r"
		expect {
			-i $sbdid "*OK" {
				write_info $infoname "sbdi-OK received"
				break
			}
			timeout {
				write_info $infoname  "$i: MODEM DOES NOT RESPOND TO AT";  
			}
		}
	}
	if { $i >= 5 } {
		#====================
		# MODEM FAILS TO RESPOND
		# ===================
		write_info $infoname "MODEM FAILS TO RESPOND, SKIP SBDI"
		return 0
	}

	set itx 0	;# we try to tx a few times
	set Ktx 0   ;# initialize the flag to 0
	set Ntx 0;  set Krx 0;  set Nrx 0;  set Lrx 0;  set Qrx 0;
	#=====================
		# KILL ECHO
	#=====================
# 	send -i $sbdid "ate0"
# 	expect {
# 		-i $sbdid "OK" {
# 			#send_user "Kill modem echo\n"
# 		}
# 	}

	#======================
	# CLEAR MEMORY
	#======================
	send -i $sbdid "at+sbdd2\r"
	expect {
		-i $sbdid "OK" {
# 		write_info $infoname "sbdi--Clear modem memory"
		}
	}
	
	#======================
	# LOAD STRING
	#=====================
	send -i $sbdid "at+sbdwt=$str\r"
	sleep 1
	#========================
	# TRANSMIT THE STRING
	#=======================
	while { $itx < 2 } {
		# REPLY: +SBDI: 1, 66, 0, 0, 0, 0
		# REPLY: +SBDIX:<MO status>,<MOMSN>,<MT status>,<MTMSN>,<MT length>,<MT queued>
		send -i $sbdid "at+sbdi\r"
		write_info $infoname "TX $itx: at+sbdi"
		set timeout 60
		expect -i $sbdid -re "\\+SBDI:(.*),(.*),(.*),(.*),(.*),(.*)\r\nOK" {
			set Ktx $expect_out(1,string)
			set Ntx $expect_out(2,string)
			set Krx $expect_out(3,string)
			set Nrx $expect_out(4,string)
			set Lrx $expect_out(5,string)
			set Qrx $expect_out(6,string)
		}
		set itx [expr $itx + 1]
		if { $Ktx == 1 } { 
			break
		}
		after 5000     ;# wait one second before retry
	}
	write_info $infoname "$str == Stat/#/itx  $Ktx/$Ntx/$itx"
	set timeout 10
	return $Ktx
}
#==================== END PROCEDURES =============================================
#!!
		#============
		# DATAPATH
		#==============
spawn -noecho getsetupinfo $setupfile "RT OUT PATH"
expect -re "(\.*)(\r)";
set datapath $expect_out(1,string)

	# INFONAME
set infoname "$env(DAQDATAFOLDER)/info.txt";
send_user "INFONAME: $infoname\n";
write_info $infoname "\n  ========== BEGIN PROGRAM $PROGRAMNAME ============="
write_info $infoname "PROGRAM $PROGRAMNAME, Version $VERSION, Editdate $EDITDATE, Runtime [timestamp -gmt -format "%Y%m%d,%H%M%S"]"
# write_info $infoname "INFORMATION FILE: $infoname"
# write_info $infoname  "RT OUT PATH: $datapath"

	# CALIBRATION FLAG
spawn -noecho getsetupinfo $setupfile "CALIBRATION EMISSIVITY"
expect -re "(\.*)(\r)";
set e_cal $expect_out(1,string)

if { $e_cal == 0 } { 
	write_info $infoname "RUN MODE."
			## PLATFORM NAME
	spawn -noecho getsetupinfo $setupfile "PLATFORM NAME"
	expect -re "(\.*)(\r)";
# 	write_info $infoname  "PLATFORM NAME: $expect_out(1,string)"

			## LOCATION ON PLATFORM
	spawn -noecho getsetupinfo $setupfile "LOCATION ON PLATFORM"
	expect -re "(\.*)(\r)";
# 	write_info $infoname  "LOCATION ON PLATFORM: $expect_out(1,string)"

			## HEIGHT ABOVE SEA LEVEL
	spawn -noecho getsetupinfo $setupfile "HEIGHT ABOVE SEA LEVEL"
	expect -re "(\.*)(\r)";
# 	write_info $infoname  "HEIGHT ABOVE SEA LEVEL: $expect_out(1,string)"

			## EXPERIMENT NAME
	spawn -noecho getsetupinfo $setupfile "EXPERIMENT NAME"
	expect -re "(\.*)(\r)";
	set expname $expect_out(1,string)
# 	write_info $infoname  "EXPERIMENT NAME: $expname"

			## GEOGRAPHIC LOCATION
	spawn -noecho getsetupinfo $setupfile "GEOGRAPHIC LOCATION"
	expect -re "(\.*)(\r)";
# 	write_info $infoname  "GEOGRAPHIC LOCATION: $expect_out(1,string)"

} else {
	write_info $infoname "CAL MODE."
}
	# PDS SERIAL HUB IP AND OFFSET
spawn -noecho getsetupinfo $setupfile "SERIAL HUB IP"
expect -re "(\.*)(\r)";
set hubip $expect_out(1,string)
write_info $infoname  "SERIAL HUB IP: $hubip"

	# SBD PORT $sbdport
spawn -noecho getsetupinfo $setupfile "SBD PORT"
expect -re "(\.*)(\r)";
set sbdport $expect_out(1,string)
write_info $infoname  "SBD PORT: $sbdport"

	## ROSR PORT
spawn -noecho getsetupinfo $setupfile "ROSR PORT"
expect -re "(\.*)(\r)";
set rosrport $expect_out(1,string)
write_info $infoname  "ROSR PORT: $rosrport"
if { $rosrport == 0 } { 
	write_info $infoname  "SIMULATE ROSR...\n";
	SpawnRosrSimulate;
} else {
	write_info $infoname  "OPEN ROSR SERIAL CONNECTION.";
	SpawnRosr $hubip $rosrport
}
		#=================
		# OPEN SET FILE NAMES AND NOTE TIME
		#=================
		# day0 = START JULIAN DAY
set day0 0
		# OPEN AVG PROGRAMS
SpawnAvgRosr $setupfile 

if { $sbdport > 0 } { 
	SpawnSBD $hubip $sbdport ;
}

		#====================
		# TIMING PARAMETERS
		#====================
		# SET dt0 SO THE FIRST AVG WILL BE TRANSMITTED
# set dt0 [expr [timestamp -gmt] -100]
set timeout 30		;# leave enough time for the scan drum to move
set sbdtxflag 1;
set txmin1 16;
set txmin2 46;
		# =====================
		# MAIN LOOP
		#======================
write_info $infoname "===== BEGIN MAIN LOOP ====="
while 1 {
#!!     # MINUTES
		set minute [timestamp -gmt -format "%M"]; 
		if {$sbdtxflag > 0 && ($minute == $txmin1 || $minute == $txmin2) } {
# 			write_info $infoname " 407 set sbdtxflag" ;
			set sbdmessage [ exec head -1 /tmp/sbd ]
			#write_info $infoname $sbdmessage
			if { $sbdport > 0 } { #v10
				set SendFlag [sbdi $sbdmessage $SBD 2]
			}
			set sbdtxflag 0;
# 			write_info $infoname " 414 clear sbdtxflag" ;
		} else {
			if { $sbdtxflag == 0 && $minute != $txmin1 && $minute != $txmin2 } {
				set sbdtxflag 1;
# 				write_info $infoname " 418 set sbdtxflag" ;
			}  
		}

		# LOOP TIME $dt
	set dt [timestamp -gmt]
			# NEW DAY
	set day1 [timestamp -gmt -format "%j" -seconds $dt]
	if {$day1 != $day0} {
		set day0 $day1
		set fname [timestamp -format "%y%m%d" -seconds $dt]
		write_info $infoname "NEW DAY $fname---"
		set rwname "$datapath/rosr_raw_$fname.txt";
		set avname "$datapath/rosr_av_$fname.txt";
		set sstname "$datapath/rosr_sst_$fname.txt";
		# v9.4 send_user "NEW DAY $fname\n"
# 		write_info $infoname "rwname = $rwname"
# 		write_info $infoname "avname = $avname"
# 		write_info $infoname "sstname = $sstname"
		# ROSR HEADER
		set str "\$WIssf,vv,etime,drum,RAD,REF,adc0,adc1,adc2,adc3,adc4,adc5,adc6,adc7,adc8,adc9,adc10,adc11,vref,t11,t12,t21,t22,pit,rol,Tanalog,Tktcase,Twindow,Tpwr,Vin,vrain,sec*chk<cr><lf>"
		set F [open $rwname a 0600]
		puts $F $str ;
		close $F
		# WIRAV HEADER
		set str "\$WIRAV,etime,vav0,vav1,vav2,vav3,k0,ksd0,k1,ksd1,k2,ksd2,k3,ksd3,t11,tsd11,t12,tsd12,t21,tsd21,t22,tsd22,T1,T2,pav,psd,rav,rsd,ang,emis*chk";
		set F [open $avname a 0600]
		puts $F $str  ;
		close $F
		#WIRST HEADER
		set str "\$WIRST,etime,vav0,vav1,vav2,vav3,k0,k1,k2,k3,T1,T2,ang,emis,ssst*chk";
		set F [open $sstname a 0600]
		puts $F $str  ;
		close $F
	}

	#================
	# EXPECT FUNCTION -- WAITING FOR RESPONSE
	# $WI033,33,00.020751,264.92, 157093,24.21,2.727,2.728,0.397,2.471,
	# 1.656,1.655,4.096,4.096,4.096,3.544,-0.000,2.814,4.942,19.87,19.87,
	# 42.86,42.90,-1.2,-1.8,18.95,18.19,200.00,200.00,14.8,-0.0,  0*18
	# ===============
	#send_user "zz test\n";
	#set timeout 4
	expect { 
		-i $ROSR
		-re "\\\$WI...*\\*..\\n?" { 
			set rawstr [string trimright $expect_out(0,string)]
			if { [string match {*\$WI*} $rawstr ] } {
				set s1 [string first "\$WI" $rawstr];
				set s2 [string first "\*" $rawstr $s1]
				set str [string range $rawstr $s1 [expr $s2+2]]
				# GPS
				#set gpstr [exec gpsgetraw] # this crashed at 00z.
				# v9.4
				set status [catch {exec gpsgetraw} gpstr ] ;
				if {$status > 0} {
					# handle an error condition ...
					set gpstr "0,0,0,0,0,0";
					#write_info $infoname "catch error, gpstr = $gpstr\n";
				}
				set str [timestamp -gmt -format "%Y,%m,%d,%H,%M,%S,"]$gpstr,$rawstr 
				set F [open $rwname a 0600]
				puts $F $str  ;
				close $F
				# SEND TO ROSRAV AND ROSRAV FOR RESPONSE
				send -i $ROSRAV "$str\r"
				expect -i $ROSRAV -re "<<.*>>\\n?" {
					set avgreply [string trimright $expect_out(0,string)]
					send_user "$avgreply\n";
				}
			} 
			if { [string match {*\$WIRAV*} $rawstr ] } {
				set s1 [string first "\$WIRAV" $rawstr];
				set s2 [string first "\*" $rawstr $s1]
				set str [string range $rawstr $s1 [expr $s2+2]]
				send_user "$str\n"; 
				set F [open $avname a 0600]
				puts $F [timestamp -gmt -format "%Y,%m,%d,%H,%M,%S,"]$str  ;
				close $F
			} 
			if { [string match {*\$WIRST*} $rawstr ] } {
				set s1 [string first "\$WIRST" $rawstr];
				set s2 [string first "\*" $rawstr $s1]
				set str [string range $rawstr $s1 [expr $s2+2]]
				send_user "$str\n"; 
				set F [open $sstname a 0600]
				puts $F [timestamp -gmt -format "%Y,%m,%d,%H,%M,%S,"]$str  ;
				close $F
			} 
		}
		#================== USER INPUT =========================================#
		-i $user_spawn_id  
		-re ".+" {
			set userstr $expect_out(0,string)
			send_user $userstr
			#=====================
			# QUIT & SEND SIGNOFF MESSAGE
			#====================
			if {[string match "*qu*" "<[string tolower $userstr]>"]} {
				write_info $infoname "USER QUIT\n==============================\n";
				exit 0;
			}
			#=====================
			# WRITE A HEADER LINE
			#====================
			if {[string match "*h*" "<[string tolower $userstr]>"]} {
				write_info $infoname "PROGRAM $PROGRAMNAME, VERSION $VERSION, EDITDATE $EDITDATE";
			}
			#=====================
			# SBD TRANSMIT
			#====================
			if {[string match "*sbd*" "<[string tolower $userstr]>"]} {
				write_info $infoname "SBD TRANSMIT $hubip, $sbdport";
				set sbdmessage [ exec head -1 /tmp/sbd ]
				write_info $infoname "$sbdmessage";
			}
		}
	}
}
